# Generated by Django 2.2.4 on 2019-08-26 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WriteupCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Uncategorized', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='WriteupArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctf', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('hint', models.TextField(blank=True)),
                ('solution', models.TextField()),
                ('tags', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('category', models.ForeignKey(default='Uncategorize', on_delete=django.db.models.deletion.SET_DEFAULT, to='blog.WriteupCategory')),
            ],
        ),
    ]
