# Generated by Django 2.2.4 on 2019-08-26 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190827_0256'),
    ]

    operations = [
        migrations.AddField(
            model_name='writeupctf',
            name='rank',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='writeupctf',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='writeupctf',
            name='trashtalk',
            field=models.TextField(blank=True),
        ),
    ]
