# Generated by Django 2.2.4 on 2019-08-28 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190827_0644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writeuptag',
            name='name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
