# Generated by Django 2.2.4 on 2019-08-28 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190828_1834'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='writeuparticle',
            options={'get_latest_by': ['ctf', 'category', 'title'], 'ordering': ['ctf', 'category', 'title']},
        ),
        migrations.AlterModelOptions(
            name='writeupctf',
            options={'ordering': ['-date', 'name']},
        ),
        migrations.AddField(
            model_name='writeupctf',
            name='img',
            field=models.ImageField(blank=True, upload_to='writeup/'),
        ),
        migrations.AlterField(
            model_name='writeuparticle',
            name='tags',
            field=models.ManyToManyField(blank=True, to='blog.WriteupTag'),
        ),
        migrations.AlterField(
            model_name='writeuptag',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
