# Generated by Django 2.2.4 on 2019-08-28 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190829_0003'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='writeuparticle',
            options={'get_latest_by': ['ctf', 'category', 'name'], 'ordering': ['ctf', 'category', 'name']},
        ),
        migrations.RenameField(
            model_name='writeuparticle',
            old_name='title',
            new_name='name',
        ),
    ]
