# Generated by Django 2.2.4 on 2019-08-28 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190829_0011'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('author', models.CharField(max_length=20)),
                ('about', models.TextField()),
                ('review', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='writeuparticle',
            options={'ordering': ['category', 'name']},
        ),
    ]
