# Generated by Django 2.2.4 on 2019-08-28 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20190829_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewarticle',
            name='author',
            field=models.TextField(),
        ),
    ]
