# Generated by Django 2.2.4 on 2019-08-28 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20190829_0145'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewarticle',
            name='img',
            field=models.ImageField(blank=True, upload_to='review/'),
        ),
        migrations.AlterField(
            model_name='reviewarticle',
            name='about',
            field=models.TextField(blank=True),
        ),
    ]
