# Generated by Django 2.2.4 on 2019-08-30 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20190829_0148'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviewarticle',
            options={'get_latest_by': '-date', 'ordering': ['-date', 'name']},
        ),
        migrations.AlterModelOptions(
            name='writeupctf',
            options={'get_latest_by': '-date', 'ordering': ['-date', 'name']},
        ),
        migrations.AddField(
            model_name='writeupctf',
            name='team',
            field=models.CharField(default='Ice1187', max_length=255),
        ),
    ]
