# Generated by Django 2.2.4 on 2019-08-31 07:20

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20190830_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writeuparticle',
            name='description',
            field=markdownx.models.MarkdownxField(blank=True),
        ),
        migrations.AlterField(
            model_name='writeuparticle',
            name='solution',
            field=markdownx.models.MarkdownxField(blank=True),
        ),
    ]
